Repository Devnilson/fisima, pull requests merged in 2020-05, with the labels that each got.

#16 Feature #7 hello world
  .gitignore
  .npmignore
  .travis.yml
  README.md
  ci/publish.sh
  package.json
  src/__tests__/hello-world.test.ts
  src/__tests__/raw-state-machine.test.ts
  src/__tests__/rxjs-state-machine.test.ts
  src/index.ts
  src/lib/index.ts
  src/machine/builder/index.ts
  src/machine/builder/node.builder.ts
  src/machine/builder/raw-state-machine.builder.ts
  src/machine/builder/rxjs-node.builder.ts
  src/machine/builder/rxjs-state-machine.builder.ts
  src/machine/model/event.ts
  src/machine/model/index.ts
  src/machine/model/node.ts
  src/machine/model/state-data.ts
  src/machine/model/state-machine.ts
  src/machine/model/transition-action.ts
  src/machine/model/transition.ts
  src/machine/raw/index.ts
  src/machine/raw/raw-node.ts
  src/machine/raw/raw-state-machine.ts
  src/machine/raw/static-destination-transition.ts
  src/machine/rxjs/index.ts
  src/machine/rxjs/rxjs-state-machine.decorator.ts
  src/machine/rxjs/rxjs-state-machine.ts
  tsconfig.json
Labels: feature

#18 Process #10 Styleguide, Prettier, Husky & Yarn
  .gitignore
  package-lock.json
  package.json
  src/index.ts
  src/lib/index.ts
  styleguide.md
  yarn.lock
Labels: feature

#17 Process #14: Add PR template
  .github/pull_request_template.md
Labels: feature

#26 chore: #24 Add prettierignore
  .prettierignore
Labels: process

#31 Create logo and include it in readme
  .github/pull_request_template.md
  README.md
  img/logoYellow400.jpg
Labels: documentation
